config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/home/about' => 'homes#about', as: "about"

  #顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
#管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用
scope module: :public do
  resources :items, only: [:index, :show]
  delete '/cart_items/reset' => '/public/cart_items#reset'
  resources :cart_items, only: [:index, :create, :update, :destroy]
  patch '/customers/quit' => '/public/customers#quit'
  resources :customers, only: [:edit, :update]
  get '/customers/my_page' => '/public/customers#show'
  get '/customers/out' => '/public/customers#out'
  resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  post '/orders/check' => '/public/orders#check'
  get '/orders/thanx' => '/public/orders#thanx'
  resources :orders, only: [:new, :create, :index, :show]

end

# 管理者用
namespace :admin do
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:index, :show, :update] do
    resources :order_details, only: [:update]
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy

validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, presence: true


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       flash[:notice] = "会員情報の変更が完了しました。"
      # 会員詳細ページへリダイレクト
        redirect_to action: :show
    else
      flash[:alert] = "会員情報の変更内容に不備があります。"
      @customer = Customer.find(params[:id])
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, :is_status)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<p id="alert"><%= alert %></p>
<div class="container">
  <div class="row">
    <div class="col-sm-8 mt-4 px-sm-0 offset-sm-1">
      <h2><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h2>
    </div>

    <div class="row mx-auto pt-4">
      <div class="col-12 text-center">
        <table class="text-left">
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
        <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch, local: true do |f| %>
          <tr>
            <th>氏名</th>
            <td><%= f.text_field :last_name, autofocus: true %></td>
            <td><%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= f.text_field :last_name_kana %></td>
            <td><%= f.text_field :first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.text_field :phone_number %></td>
          </tr>
          <tr>
            <th class="pr-4">メールアドレス</th>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_status, :false, checked: true %>
              <%= f.label :is_status, "有効", {value: :false, style: "display: inline-block;"} %>
              <%= f.radio_button :is_status, :true %>
    　         <%= f.label :is_status, "退会", {value: :true, style: "display: inline-block;"} %>
    　       </td>
          </tr>
        </table>
          <%= f.submit "変更を保存", class: "btn btn-sm btn-success" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="col-sm-8 mt-4 px-sm-0 offset-sm-1">
    <h2>会員一覧</h2>
  </div>
    <div class="col-sm-10 mt-4 offset-2">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customer| %>
        <tbody>
          <tr>
            <td><%= customer.id %></td>
            <!--リンクを実装する-->
            <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class: "border-bottom border-brack text-dark" %></td>
            <td><%= customer.email %></td>
            <!--true=退会済み、false=有効-->
              <% if customer.is_status == true %>
                <td class="text-secondary">退会</td>
              <% else %>
                <td class="text-success">有効</td>
              <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>
      <div class="row justify-content-center">
        <%= paginate @customers %>
      </div>
    </div>
</div>

app/views/admin/customers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-sm-8 mt-4 px-sm-0 offset-sm-1">
      <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    </div>

    <div class="col-sm-8 mt-4 px-sm-0 offset-sm-3">
      <div class="row">
        <table>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @customer.last_name + "　" + @customer.first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= @customer.last_name_kana + "　" + @customer.first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </t>
          <tr>
            <th>電話番号</th>
            <td><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <th class="pr-5">メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <!--true=退会済み、false=有効-->
              <% if @customer.is_status == true %>
                <td class="text-secondary">退会</td>
              <% else %>
                <td class="text-success">有効</td>
              <% end %>
          </tr>
        </table>
      </div>
    </div>
    <div class="col-sm-8 mt-4 px-sm-0 offset-sm-3">
      <div class="row mx-auto">
        <div class="actions">
          <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-sm btn-success" %>
        </div>

        <div class="actions ml-5">
          <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-sm btn-primary" %>
        </div>
      </div>
    </div>

  </div>
</div>