config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/home/about' => 'homes#about', as: "about"

  #顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
#管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用
scope module: :public do
  resources :items, only: [:index, :show]
  delete '/cart_items/reset' => '/public/cart_items#reset'
  resources :cart_items, only: [:index, :create, :update, :destroy]
  patch '/customers/quit' => '/public/customers#quit'
  resources :customers, only: [:edit, :update]
  get '/customers/my_page' => '/public/customers#show'
  get '/customers/out' => '/public/customers#out'
  resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  post '/orders/check' => '/public/orders#check'
  get '/orders/thanx' => '/public/orders#thanx'
  resources :orders, only: [:new, :create, :index, :show]

end

# 管理者用
namespace :admin do
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:index, :show, :update] do
    resources :order_details, only: [:update]
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, :address, :name, presence: true
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates :customer_id, :item_id, :amount, presence: true
  validates :amount, numericality: {only_integer: true }
  has_one_attached :image
  def subtotal
    item.with_tax_price * amount
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpeg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy

validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, presence: true


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_many :orders, through: :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: {only_integer: true }
  validates :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :name, :postal_code, :address, presence: true
  enum payment_method: {
    credit_card: 0,
    transfer: 1
  }

  enum status: { "入金待ち":0, "入金確認":1, "製作中":2, "発送準備中":3, "発送済":4 }

  enum address_option:[:"ご自身の住所", :"登録済みの住所から選択", :"新しいお届け先"]
  def ship_cost
    self.shipping_cost = 800
  end
  class << self
    def localed_statuses
      statuses.keys.map do |s|
        [ApplicationController.helpers.t("status.article.#{s}"), s]
      end
    end
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { "製作不可":0, "製作待ち":1, "製作中":2, "製作完了":3 }


  class << self
    def localed_making_statuses
      making_statuses.keys.map do |s|
        [ApplicationController.helpers.t("making_status.article.#{s}"), s]
      end
    end
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
      flash[:notice] = "変更内容を更新しました。"
      redirect_to admin_genres_path
   else
      flash[:alert] = "変更内容に不備があります。"
      render :edit
   end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
   if @item.save
       flash[:notice] = "商品の新規登録が完了しました。"
       redirect_to admin_item_path(@item.id)
   else
       flash[:alert] = "商品の新規登録内容に不備があります。"
       render :new
   end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品詳細の変更が完了しました。"
      redirect_to admin_item_path(@item.id)
    else
      flash[:alert] = "商品詳細の変更内容に不備があります。"
      render :edit
    end
  end


  def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
    # 商品をidの逆順で並べ替えて、4件取得
    @items = Item.order(id: :DESC).limit(4)

  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom border-top p-3 mb-2 bg-info text-white">
  <div class='container mt-2'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>
    		  <span style="font-size : 15pt">
    		   nagano_cake
    		  </span>
    		</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-info">
  <nav class="navbar navbar-expand-lg border-bottom">
    <div class="container">
      <div class="mr-5 border rounded p-2 bg-warning border-white">
        <% if admin_signed_in? %>
        <%= link_to "NaganoCAKE", admin_orders_path, class:"header-title navbar-brand"%>
        <% else %>
        <%= link_to "NaganoCAKE", root_path, class:"header-title navbar-brand"%>
        <% end %>
      </div>
      <div class="text-center font-weight-bold">
        <% if customer_signed_in? %>
          ようこそ、<%= current_customer.last_name %>さん！
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <!--顧客側がログインした場合-->
        <% if customer_signed_in? %>
          <li>
            <%= link_to customers_my_page_path, class: 'nav-link text-white border rounded mr-2 bg-success' do %>
            <i class="fas fa-users"></i>マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to items_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-cheese"></i>商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to cart_items_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-shopping-cart"></i>カート
            <% end %>
          </li>
          <li>
            <%= link_to  destroy_customer_session_path, method: :delete, class: 'nav-link text-white border rounded ml-2 bg-success' do %>
            <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>

        <!--管理者がログインしていた場合-->
        <% elsif admin_signed_in? %>
           <li>
            <%= link_to admin_items_path, class: 'nav-link text-white border rounded mr-2 bg-success' do %>
            <i class="fas fa-cheese"></i>商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_customers_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-users"></i>会員一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_orders_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-list-alt"></i>注文履歴一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-list-ul"></i>ジャンル一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-white border rounded ml-2 bg-success' do %>
            <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>
        <!--ログインしていない場合-->
        <% else %>
          <li>
            <%= link_to about_path, class: 'nav-link text-white border rounded mr-2 bg-success' do %>
            <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-cheese"></i>商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path,class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-user-plus"></i>新規登録
            <% end %>
          </li>
          <li>
            <%= link_to customer_session_path ,class: 'nav-link text-white border rounded ml-2 bg-success' do %>
            <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
          <li class="ml-2">
            <%= form_with url: items_path, method: :get, local: true do |f| %>
            <input id="sbox4"  id="s" name="s" type="text" placeholder="Search">
            <button id="sbtn4" type="submit"><i class="fas fa-search"></i>
            </button>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
     <%= render 'layouts/footer' %>
  </body>
</html>